[workspace]
[package]
name = "c-sp1"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.170"
sp1-zkvm = "=4.1.1"

[build-dependencies]
bindgen = "0.71.1"
cc = "1.2.16"

[features]
sp1 = []
