[workspace]
[package]
name = "merkle"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-zkvm = "=4.1.1"
risc0-zkvm = { version = "1.2.3", default-features = false, features = ["std"] }
rs_merkle = "1.5.0"

[features]
risc0 = []
sp1 = []
