[package]
name = "zkvm-host"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "=1.2.3", default-features = false, features = ["std"] }
sp1-zkvm = "=4.1.1"

[lib]
name = "zkvmlib"
path = "src/lib.rs"

[[bin]]
name = "c"
path = "src/main.rs"

[features]
risc0 = []
sp1 = []
